---
# Configuration settings to enable communication to the GK's User Management module
# Connecto to GK API
address: tng-api-gtw # <set_UM_Adapter_address_here> # tng-api-gtw
port: 5000 # <set_UM_Adapter_port_here>
api_ver: /api/v2

# Gatekeeper's User Management endpoints
public_key_path: /micro-services/public-key  # /api/v2/micro-services/public-key
registration_path: /micro-services
login_path: /micro-services
# authorization_path: /authorize

# Component identifiers and credentials
# (sample)
catalogue_client: tng-cat
catalogue_secret: 1234
