swagger: "2.0"
info:
  title: "5GTANGO CATALOGUE API"
  description: "This is a proposal for the SONATA's SP API"
  version: "1.0.0"
host: sp.sonata-nfv.eu
schemes:
  - http
basePath: /api
produces:
  - application/json